Groovy REPL: script file detection/execution fails, fixes #1139
jline/jline3 pull request #1140
Opened 2024-12-20 14:18 UTC by mattirn

2025-01-13 06:13 UTC, gnodet requested changes

2025-01-13 06:13 UTC, gnodet commented on console/src/main/java/org/jline/console/impl/ConsoleEngineImpl.java
Can we avoid the empty block on the caught exception ? Maybe at least log it ?

2025-02-01 09:01 UTC, mattirn commented
Moved script file detection to class `ConsoleEngineImpl.ScriptFile` and added default implementation for `execute(Path file, ...)` in `ScriptEngine` interface.

2025-04-25 19:52 UTC, gnodet approved these changes

2025-04-26 05:07 UTC, merged