[JLINE-730] Support for comments in DefaultParser
jline/jline3 pull request #731
Opened 2021-10-21 13:40 UTC by snuyanzin

The PR makes it possible to set multiline comment start and end.
Also it allows to specify several one-line comments as several engines support several one-line comments

fixes #730

2021-10-28 11:39 UTC, snuyanzin commented on reader/src/main/java/org/jline/reader/impl/DefaultParser.java
> +    private int handleDelimiterAndGetRawWordLength(StringBuilder current, List<String> words, int rawWordStart, int rawWordCursor, int rawWordLength, int pos) {
I extracted this into a method as now this code block is used in 2 places.
In case you have a better method name suggestion  I would consider that

2021-10-30 20:09 UTC, snuyanzin commented
Probably also need to check that block start and end differ from one line comments and from brackets and quotes

2021-11-06 15:45 UTC, mattirn commented
> Probably also need to check that block start and end differ from one line comments and from brackets and quotes

Partially true... brackets can be used as block comment delimiters if they do not have any other use in CLI. I would not add any other validity checks for comment delimiters. IMHO checks would just make the code more complicate to follow without bringing much more value for implementation. I guess that the 'standard' comment delimiters (like //, #, /*, */, ...) will be mostly adopted in Jline CLIs

2021-11-06 16:11 UTC, mattirn requested changes
I think we should throw `EOFError` also for missing opening block comment:
```
            if (startBlockCommentMissing) {
                throw new EOFError(-1, -1, "Missing opening block comment delimiter",
                        "missing: " + blockCommentStart);
            }
```
Please, change also the line 
https://github.com/jline/jline3/blob/9c9d638ac340de7a06b9c33d65ae8356eca65eea/reader/src/main/java/org/jline/reader/impl/DefaultParser.java#L379
to
```
                throw new EOFError(-1, -1, "Missing closing block comment delimiter",
                        "add: " + blockCommentEnd);
```

2021-11-08 18:00 UTC, merged